"""initial_schema

Revision ID: 3470b4295b9c
Revises: 
Create Date: 2026-07-06 16:17:42.904941

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3470b4295b9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=36), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_org_action', 'audit_log', ['org_id', 'action'], unique=False)
    op.create_index('ix_audit_resource', 'audit_log', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_user', 'audit_log', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('risk_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_provider', sa.String(length=20), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(slug) >= 2', name='ck_organizations_slug_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','reviewer','viewer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_org_id_role', 'users', ['org_id', 'role'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('counterparty', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('has_images', sa.Boolean(), nullable=False),
    sa.Column('has_tables', sa.Boolean(), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=True),
    sa.Column('renewal_notice_days', sa.Integer(), nullable=True),
    sa.Column('overall_risk', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('processing_job_id', sa.String(length=36), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_contracts_risk_score'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_created_at'), 'contracts', ['created_at'], unique=False)
    op.create_index('ix_contracts_org_expiry', 'contracts', ['org_id', 'expiry_date'], unique=False)
    op.create_index('ix_contracts_org_risk', 'contracts', ['org_id', 'risk_score'], unique=False)
    op.create_index('ix_contracts_org_status', 'contracts', ['org_id', 'status'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('device_hint', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.create_index('ix_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'revoked'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('clause_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('chunk_level', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('suggested_revision', sa.Text(), nullable=True),
    sa.Column('is_standard', sa.Boolean(), nullable=True),
    sa.Column('deviation_notes', sa.Text(), nullable=True),
    sa.Column('extraction_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('judge_verdict', sa.String(length=20), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vector_id', sa.String(length=36), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_clauses_risk_score'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clauses_contract_type', 'clauses', ['contract_id', 'clause_type'], unique=False)
    op.create_index(op.f('ix_clauses_created_at'), 'clauses', ['created_at'], unique=False)
    op.create_index('ix_clauses_org_flagged', 'clauses', ['org_id', 'flagged_for_review'], unique=False)
    op.create_index('ix_clauses_org_risk', 'clauses', ['org_id', 'risk_score'], unique=False)
    op.create_table('user_contract_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'contract_id', name='uq_user_contract')
    )
    op.create_index('ix_assignments_contract', 'user_contract_assignments', ['contract_id'], unique=False)
    op.create_index('ix_assignments_user', 'user_contract_assignments', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=False),
    sa.Column('is_positive', sa.Boolean(), nullable=False),
    sa.Column('feedback_target', sa.String(length=50), nullable=False),
    sa.Column('original_value', sa.String(length=200), nullable=True),
    sa.Column('suggested_value', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_feedback_clause', 'feedback', ['clause_id'], unique=False)
    op.create_index('ix_feedback_org', 'feedback', ['org_id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('clause_id', sa.UUID(), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('party', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('recurrence', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_created_at'), 'obligations', ['created_at'], unique=False)
    op.create_index(op.f('ix_obligations_due_date'), 'obligations', ['due_date'], unique=False)
    op.create_index('ix_obligations_org_due', 'obligations', ['org_id', 'due_date'], unique=False)
    op.create_index('ix_obligations_org_status', 'obligations', ['org_id', 'status'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('obligation_id', sa.UUID(), nullable=True),
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=20), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trigger_date', sa.Date(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['obligation_id'], ['obligations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_org_trigger', 'alerts', ['org_id', 'trigger_date'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_org_trigger', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_obligations_org_status', table_name='obligations')
    op.drop_index('ix_obligations_org_due', table_name='obligations')
    op.drop_index(op.f('ix_obligations_due_date'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_created_at'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index('ix_feedback_org', table_name='feedback')
    op.drop_index('ix_feedback_clause', table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_assignments_user', table_name='user_contract_assignments')
    op.drop_index('ix_assignments_contract', table_name='user_contract_assignments')
    op.drop_table('user_contract_assignments')
    op.drop_index('ix_clauses_org_risk', table_name='clauses')
    op.drop_index('ix_clauses_org_flagged', table_name='clauses')
    op.drop_index(op.f('ix_clauses_created_at'), table_name='clauses')
    op.drop_index('ix_clauses_contract_type', table_name='clauses')
    op.drop_table('clauses')
    op.drop_index('ix_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_contracts_org_status', table_name='contracts')
    op.drop_index('ix_contracts_org_risk', table_name='contracts')
    op.drop_index('ix_contracts_org_expiry', table_name='contracts')
    op.drop_index(op.f('ix_contracts_created_at'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index('ix_users_org_id_role', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_audit_user', table_name='audit_log')
    op.drop_index('ix_audit_resource', table_name='audit_log')
    op.drop_index('ix_audit_org_action', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
